### ISSUE TITLE
segfault on joining room

### ISSUE THREAD

**Issue by Evidlo** [tulir/gomuks#108]
```
[evan@blackbox tmp] gomuks 
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x76c56e]

goroutine 14 [running]:
maunium.net/go/gomuks/debug.Recover()
	/home/evan/resources/go/src/maunium.net/go/gomuks/debug/debug.go:109 +0x94
panic(0xaa6ec0, 0x113d0e0)
	/usr/lib/golang/src/runtime/panic.go:679 +0x1b2
maunium.net/go/gomuks/matrix.(*Container).JoinRoom(0xc0002cd440, 0xc0042bdef6, 0x1c, 0x0, 0x0, 0x1, 0xd600000000000000, 0xc000478ea0)
	/home/evan/resources/go/src/maunium.net/go/gomuks/matrix/matrix.go:679 +0xce
maunium.net/go/gomuks/ui.cmdJoin(0xc000306120)
	/home/evan/resources/go/src/maunium.net/go/gomuks/ui/commands.go:369 +0x79
maunium.net/go/gomuks/ui.(*CommandProcessor).HandleCommand(0xc0005334a0, 0xc000306120)
	/home/evan/resources/go/src/maunium.net/go/gomuks/ui/command-processor.go:155 +0x11a
created by maunium.net/go/gomuks/ui.(*RoomView).InputSubmit
	/home/evan/resources/go/src/maunium.net/go/gomuks/ui/room-view.go:400 +0x98
```

This always happens the first time I try to join a room.  When I restart gomuks and try to join again, it works.

**Comment by tulir** [comment]
Probably fixed by 2a4755b712698177dc5c822d8b77e5bfbc7d7a8e
