### ISSUE TITLE
Cannot run inside tmux

### ISSUE THREAD

**Issue by facadeproof** [tulir/gomuks#171]
```sh
panic: exit status 1 [recovered]
        panic: exit status 1

goroutine 1 [running]:
maunium.net/go/gomuks/debug.Recover()
        /opt/gomuks/debug/debug.go:109 +0x94
panic(0xc07c20, 0xc000492ce0)
        /usr/lib/go/src/runtime/panic.go:969 +0x166
main.(*Gomuks).Start(0xc0000b9050)
        /opt/gomuks/gomuks.go:116 +0x149
main.main()
        /opt/gomuks/main.go:77 +0x484
```
Everything is working fine outside of `tmux`. I've made sure to do a `git pull --rebase` to get the latest version of `gomuks`. Compiled from source on Void.

**Comment by facadeproof** [comment]
Closing. Was using wrong `$TERM`, sorry.
