### ISSUE TITLE
Reproducible Error: When switching room with Ctrl + K and then pressing # and then Shift + tab

### ISSUE THREAD

**Issue by jgarte** [tulir/gomuks#182]
gomuks version: 0.1.0
operating system: NixOS

I get a reproducible error when switching rooms with `Ctrl + K`.
I start search for rooms that start with `#` 
Subsequently pressing `Shift + Tab` gives me the following error:

```shell
panic: runtime error: index out of range [-1] [recovered]
        panic: runtime error: index out of range [-1] [recovered]
        panic: runtime error: index out of range [-1]

goroutine 1 [running]:
maunium.net/go/gomuks/debug.Recover()
        /build/source/debug/debug.go:109 +0x94
panic(0xbef860, 0xc001e11ca0)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14.2/share/go/src/runtime/panic.go:969 +0x166
maunium.net/go/mauview.(*Application).Start.func1(0xc0000c3500)
        /build/source/vendor/maunium.net/go/mauview/application.go:99 +0x82
panic(0xbef860, 0xc001e11ca0)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14.2/share/go/src/runtime/panic.go:969 +0x166
maunium.net/go/gomuks/ui.(*FuzzySearchModal).OnKeyEvent(0xc00024fd00, 0xedc5a0, 0xc0026f0980, 0x7ffb9e18fb98)
        /build/source/ui/fuzzy-search-modal.go:138 +0x68d
maunium.net/go/gomuks/ui.(*MainView).OnKeyEvent(0xc000236370, 0xedc5a0, 0xc0026f0980, 0x0)
        /build/source/ui/view-main.go:182 +0x3ca
maunium.net/go/mauview.(*Application).Start(0xc0000c3500, 0x0, 0x0)
        /build/source/vendor/maunium.net/go/mauview/application.go:150 +0x3c1
maunium.net/go/gomuks/ui.(*GomuksUI).Start(0xc00057f5f0, 0xcf1d58, 0xc00057f5c0)
        /build/source/ui/ui.go:73 +0x2f
main.(*Gomuks).Start(0xc00057f5c0)
        /build/source/gomuks.go:115 +0x11c
main.main()
        /build/source/main.go:77 +0x484
```

I found this bug by mistake. I usually just press `Tab` instead of `Shift + Tab`.

**Comment by jgarte** [comment]
Let me know if you need anymore information on my end.
