### ISSUE TITLE
Panic on running after update

### ISSUE THREAD

**Issue by serussell** [tulir/gomuks#20]
Upgrading to 0cdde557a3ed7624de31aa844929037b65e1fe11, gomuks briefly displays the UI and then panics:

```
runtime error: index out of range
goroutine 14 [running]:
runtime/debug.Stack(0x896fc0, 0xc423698000, 0xc42327d6e0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
maunium.net/go/gomuks/debug.PrettyPanic(0x7d1400, 0xa6e660)
        <ELIDED>/src/maunium.net/go/gomuks/debug/debug.go:80 +0x292
main.(*Gomuks).Recover(0xc4201b2990)
        <ELIDED>/src/maunium.net/go/gomuks/gomuks.go:120 +0x69
panic(0x7d1400, 0xa6e660)
        /usr/local/go/src/runtime/panic.go:505 +0x229
maunium.net/go/gomuks/ui/messages/parser.(*TagArray).Pop(0xc422b3c5e0, 0xc422e64a58, 0x1, 0x1)
        <ELIDED>/src/maunium.net/go/gomuks/ui/messages/parser/htmltagarray.go:67 +0x2cc
maunium.net/go/gomuks/ui/messages/parser.(*MatrixHTMLProcessor).HandleEndTag(0xc4233361e0, 0xc422e64a58, 0x1)
        <ELIDED>/src/maunium.net/go/gomuks/ui/messages/parser/htmlparser.go:120 +0x5e
maunium.net/go/gomuks/lib/htmlparser.HTMLParser.Process(0xc42363a270, 0x89c2c0, 0xc4233361e0)
        <ELIDED>/src/maunium.net/go/gomuks/lib/htmlparser/htmlparser.go:137 +0x22a
maunium.net/go/gomuks/ui/messages/parser.ParseHTMLMessage(0xc4200be180, 0xc42327dea0, 0x16, 0x1, 0xc423282658)
        <ELIDED>/src/maunium.net/go/gomuks/ui/messages/parser/htmlparser.go:183 +0x206
maunium.net/go/gomuks/ui/messages/parser.ParseMessage(0x89c260, 0xc4201b2990, 0xc4200be180, 0xc42327dea0, 0xc42365cfc0, 0xc4235761f8)
        <ELIDED>/src/maunium.net/go/gomuks/ui/messages/parser/parser.go:62 +0x2c9
maunium.net/go/gomuks/ui/messages/parser.ParseEvent(0x89c260, 0xc4201b2990, 0xc4200be180, 0xc42327dea0, 0xc4236202c0, 0x1)
        <ELIDED>/src/maunium.net/go/gomuks/ui/messages/parser/parser.go:40 +0x10a
maunium.net/go/gomuks/ui.(*MainView).ParseEvent(0xc422ff3a70, 0x89d2c0, 0xc4235720c0, 0xc42327dea0, 0x7f31e03ec4c0, 0xc4236202c0)
        <ELIDED>/src/maunium.net/go/gomuks/ui/view-main.go:470 +0x64
maunium.net/go/gomuks/ui.(*MainView).LoadHistory(0xc422ff3a70, 0xc4232b65e0, 0x1e, 0x1)
        <ELIDED>/src/maunium.net/go/gomuks/ui/view-main.go:456 +0x4c9
created by maunium.net/go/gomuks/ui.(*MainView).addRoom
        <ELIDED>/src/maunium.net/go/gomuks/ui/view-main.go:323 +0x494
```

**Comment by tulir** [comment]
It was probably either an unpaired closing HTML tag or a closing tag for a tag that can be implicitly self-closing. Please test that commit and close the issue if it's fixed.

**Comment by serussell** [comment]
Sadly, not.

```
runtime error: invalid memory address or nil pointer dereference
goroutine 12 [running]:
runtime/debug.Stack(0x896f60, 0xc4233528c0, 0xc423edb720)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
maunium.net/go/gomuks/debug.PrettyPanic(0x7d13e0, 0xa6e620)
        <ELIDED>/src/maunium.net/go/gomuks/debug/debug.go:80 +0x292
main.(*Gomuks).Recover(0xc4201b4990)
        <ELIDED>/src/maunium.net/go/gomuks/gomuks.go:120 +0x69
panic(0x7d13e0, 0xa6e620)
        /usr/local/go/src/runtime/panic.go:505 +0x229
maunium.net/go/gomuks/ui/messages/parser.(*MatrixHTMLProcessor).HandleEndTag(0xc4233311d0, 0xc42498f998, 0x1)
        <ELIDED>/src/maunium.net/go/gomuks/ui/messages/parser/htmlparser.go:122 +0x68
maunium.net/go/gomuks/lib/htmlparser.HTMLParser.Process(0xc422ea01a0, 0x89c260, 0xc4233311d0)
        <ELIDED>/src/maunium.net/go/gomuks/lib/htmlparser/htmlparser.go:137 +0x22a
maunium.net/go/gomuks/ui/messages/parser.ParseHTMLMessage(0xc4200c2180, 0xc423edbea0, 0x16, 0x1, 0xc423045f18)
        <ELIDED>/src/maunium.net/go/gomuks/ui/messages/parser/htmlparser.go:183 +0x206
maunium.net/go/gomuks/ui/messages/parser.ParseMessage(0x89c200, 0xc4201b4990, 0xc4200c2180, 0xc423edbea0, 0xc424b50900, 0xc422ac08b8)
        <ELIDED>/src/maunium.net/go/gomuks/ui/messages/parser/parser.go:62 +0x2c9
maunium.net/go/gomuks/ui/messages/parser.ParseEvent(0x89c200, 0xc4201b4990, 0xc4200c2180, 0xc423edbea0, 0xc4248b42c0, 0x1)
        <ELIDED>/src/maunium.net/go/gomuks/ui/messages/parser/parser.go:40 +0x10a
maunium.net/go/gomuks/ui.(*MainView).ParseEvent(0xc422ff5a70, 0x89d260, 0xc42286f180, 0xc423edbea0, 0x7f2c4817bbd0, 0xc4248b42c0)
        <ELIDED>/src/maunium.net/go/gomuks/ui/view-main.go:470 +0x64
maunium.net/go/gomuks/ui.(*MainView).LoadHistory(0xc422ff5a70, 0xc423016880, 0x1e, 0x1)
        <ELIDED>/src/maunium.net/go/gomuks/ui/view-main.go:456 +0x4c9
created by maunium.net/go/gomuks/ui.(*MainView).addRoom
        <ELIDED>/src/maunium.net/go/gomuks/ui/view-main.go:323 +0x494
```

**Comment by tulir** [comment]
How about now?

**Comment by serussell** [comment]
That did the trick, thanks!
