### ISSUE TITLE
Crash on launch (codeblockToEntity)

### ISSUE THREAD

**Issue by MayeulC** [tulir/gomuks#237]
Gomuks is installed from the AUR -git package

I can't launch gomuks anymore, it crashes with the following log. It started crashing at some point, possibly related to an edited codeblock. I updated to latest git, no dice.

The backtrace doesn't look that useful, not sure how to make it more helpful?

```
% gomuks                                                                                                                                                                                        :)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xad941b]

goroutine 14 [running]:
maunium.net/go/gomuks/debug.Recover()
	debug/debug.go:109 +0x98
panic(0xc14060, 0x1314060)
	/usr/lib/go/src/runtime/panic.go:969 +0x175
maunium.net/go/gomuks/ui/messages/html.(*htmlParser).codeblockToEntity(0xc000bcdbc8, 0xc004967180, 0xcbaade, 0x3)
	ui/messages/html/parser.go:323 +0x3b
maunium.net/go/gomuks/ui/messages/html.(*htmlParser).tagNodeToEntity(0xc000bcdbc8, 0xc004967180, 0xc000bcd950, 0x453c85)
	ui/messages/html/parser.go:358 +0x2c7
maunium.net/go/gomuks/ui/messages/html.(*htmlParser).singleNodeToEntity(0xc000bcdbc8, 0xc004967180, 0x2, 0x2)
	ui/messages/html/parser.go:385 +0x312
maunium.net/go/gomuks/ui/messages/html.(*htmlParser).nodeToEntities(0xc000bcdbc8, 0xc004967180, 0x4, 0xf34000, 0xc000020050)
	ui/messages/html/parser.go:404 +0x79
maunium.net/go/gomuks/ui/messages/html.(*htmlParser).tagNodeToEntity(0xc000bcdbc8, 0xc004966fc0, 0xc8c320, 0x7f9098f1d701)
	ui/messages/html/parser.go:369 +0xa6
maunium.net/go/gomuks/ui/messages/html.(*htmlParser).singleNodeToEntity(0xc000bcdbc8, 0xc004966fc0, 0x0, 0x0)
	ui/messages/html/parser.go:385 +0x312
maunium.net/go/gomuks/ui/messages/html.(*htmlParser).Parse(0xc000bcdbc8, 0xc00464a3f0, 0x66, 0x1, 0xc0049414b0)
	ui/messages/html/parser.go:429 +0xd8
maunium.net/go/gomuks/ui/messages/html.Parse(0xc00011f118, 0xc000597c20, 0xc00458fb90, 0xc0049550e0, 0x1a, 0xc00333f400, 0x15, 0xc000bcdc90, 0xc000bcdcd0)
	ui/messages/html/parser.go:447 +0x18a
maunium.net/go/gomuks/ui/messages.ParseMessage(0xf48540, 0xc0002801c0, 0xc000597c20, 0xc00495a660, 0xc00333f400, 0x15, 0x41aa1b)
	ui/messages/parser.go:207 +0x3de
maunium.net/go/gomuks/ui/messages.directParseEvent(0xf48540, 0xc0002801c0, 0xc000597c20, 0xc00495a660, 0xc000bd2000)
	ui/messages/parser.go:83 +0x35b
maunium.net/go/gomuks/ui/messages.ParseEvent(0xf48540, 0xc0002801c0, 0xf44960, 0xc0004af760, 0xc000597c20, 0xc00495a660, 0xc000bd2010)
	ui/messages/parser.go:48 +0x50
maunium.net/go/gomuks/ui.(*RoomView).parseEvent(...)
	ui/room-view.go:859
maunium.net/go/gomuks/ui.(*RoomView).AddHistoryEvent(0xc002deadc0, 0xc00495a660)
	ui/room-view.go:863 +0x6d
maunium.net/go/gomuks/ui.(*MainView).LoadHistory(0xc0004af760, 0xc000558900, 0x1e)
	ui/view-main.go:462 +0x1ad
created by maunium.net/go/gomuks/ui.(*MainView).switchRoom
	ui/view-main.go:268 +0x21f
```

**Comment by MayeulC** [comment]
I recompiled with the debug symbols on by adding the following to the PKGBUILD of the AUR package:

```
options=(debug !strip)
```

When running in gdb, I obtain the following backtrace:

```
Thread 7 "gomuks" received signal SIGSEGV, Segmentation fault.
                                                              [Switching to Thread 0x7fffc97fa640 (LWP 323768)]
0x0000000000ad941b in maunium.net/go/gomuks/ui/messages/html.(*htmlParser).codeblockToEntity (parser=0xc00469bbc8, 
    node=0xc004a91340, ~r1=...) at ui/messages/html/parser.go:323
323	ui/messages/html/parser.go: No such file or directory.
(gdb) bt
#0  0x0000000000ad941b in maunium.net/go/gomuks/ui/messages/html.(*htmlParser).codeblockToEntity (parser=0xc00469bbc8, 
    node=0xc004a91340, ~r1=...) at ui/messages/html/parser.go:323
#1  0x0000000000ad9987 in maunium.net/go/gomuks/ui/messages/html.(*htmlParser).tagNodeToEntity (parser=0xc00469bbc8, 
    node=0xc004a91340, ~r1=...) at ui/messages/html/parser.go:358
#2  0x0000000000ada152 in maunium.net/go/gomuks/ui/messages/html.(*htmlParser).singleNodeToEntity (
    parser=0xc00469bbc8, node=0xc004a91340, ~r1=...) at ui/messages/html/parser.go:385
#3  0x0000000000ada219 in maunium.net/go/gomuks/ui/messages/html.(*htmlParser).nodeToEntities (parser=0xc00469bbc8, 
    node=0xc004a91340, entities=...) at ui/messages/html/parser.go:404
#4  0x0000000000ad9766 in maunium.net/go/gomuks/ui/messages/html.(*htmlParser).tagNodeToEntity (parser=0xc00469bbc8, 
    node=0xc004a91180, ~r1=...) at ui/messages/html/parser.go:369
#5  0x0000000000ada152 in maunium.net/go/gomuks/ui/messages/html.(*htmlParser).singleNodeToEntity (
    parser=0xc00469bbc8, node=0xc004a91180, ~r1=...) at ui/messages/html/parser.go:385
#6  0x0000000000ada4b8 in maunium.net/go/gomuks/ui/messages/html.(*htmlParser).Parse (parser=0xc00469bbc8, 
    htmlData="[D] &lt;@Funeral&gt; @33YN2 html tags. <code></code> for single line stuff, <pre></pre> for multi-line", 
    ~r1=...) at ui/messages/html/parser.go:429
#7  0x0000000000ada6ca in maunium.net/go/gomuks/ui/messages/html.Parse (prefs=0xc000195118, room=0xc0004f1c20, 
    content=0xc0046afb90, sender=..., senderDisplayname="Pine64 Protocol Droid", ~r5=...)
    at ui/messages/html/parser.go:447
#8  0x0000000000ae37fe in maunium.net/go/gomuks/ui/messages.ParseMessage (matrix=..., room=0xc0004f1c20, 
    evt=0xc004a80660, displayname="Pine64 Protocol Droid", ~r4=<optimized out>) at ui/messages/parser.go:207
#9  0x0000000000ae1afb in maunium.net/go/gomuks/ui/messages.directParseEvent (matrix=..., room=0xc0004f1c20, 
    evt=0xc004a80660, ~r3=<optimized out>) at ui/messages/parser.go:83
#10 0x0000000000ae1470 in maunium.net/go/gomuks/ui/messages.ParseEvent (matrix=..., mainView=..., room=0xc0004f1c20, 
    evt=0xc004a80660, ~r4=<optimized out>) at ui/messages/parser.go:48
#11 0x0000000000b8744d in maunium.net/go/gomuks/ui.(*RoomView).parseEvent (view=0xc002516c80, evt=0xc004a80660)
    at ui/room-view.go:859
#12 maunium.net/go/gomuks/ui.(*RoomView).AddHistoryEvent (view=0xc002516c80, evt=0xc004a80660) at ui/room-view.go:863
#13 0x0000000000b9098d in maunium.net/go/gomuks/ui.(*MainView).LoadHistory (view=0xc00062d6b0, roomID=...)
    at ui/view-main.go:462
#14 0x00000000004745a1 in runtime.goexit () at /usr/lib/go/src/runtime/asm_amd64.s:1374
#15 0x000000c00062d6b0 in ?? ()
#16 0x000000c0003d5020 in ?? ()
#17 0x000000000000001e in ?? ()
#18 0x0000000000000000 in ?? ()
(gdb) quit
```

That's probably a bit better, I don't know if that's more useful?

**Comment by tulir** [comment]
Go stack traces usually contain all the relevant information (file name and line number) regardless of how it was built

**Comment by MayeulC** [comment]
Thanks for the fix, I confirm his works :tada:
