### ISSUE TITLE
Immediate crash on login

### ISSUE THREAD

**Issue by ghost** [tulir/gomuks#244]
Hello,

After opening gomuks in a clean environment, installed from the arch AUR package, the client crashes immediately after login, during the initial sync, with the following stack trace:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x61 pc=0x8e1eec]

goroutine 1 [running]:
maunium.net/go/gomuks/debug.Recover()
	debug/debug.go:109 +0x98
panic(0xc15080, 0x1316060)
	/usr/lib/go/src/runtime/panic.go:969 +0x1b9
maunium.net/go/mauview.(*Application).Start.func1(0xc0003f94a0)
	/home/sparrowhawk/projects/soft/go/pkg/mod/maunium.net/go/mauview@v0.1.2/application.go:104 +0x87
panic(0xc15080, 0x1316060)
	/usr/lib/go/src/runtime/panic.go:969 +0x1b9
maunium.net/go/mauview.(*ProxyScreen).SetContent(0xc0005947c0, 0x0, 0x0, 0x2551, 0x0, 0x0, 0x0, 0x0)
	/home/sparrowhawk/projects/soft/go/pkg/mod/maunium.net/go/mauview@v0.1.2/screen.go:112 +0x6c
maunium.net/go/mauview.(*Box).drawBorder(0xc0001ca000, 0xf45920, 0xc0005947c0)
	/home/sparrowhawk/projects/soft/go/pkg/mod/maunium.net/go/mauview@v0.1.2/box.go:154 +0x2a2
maunium.net/go/mauview.(*Box).Draw(0xc0001ca000, 0xf45920, 0xc0005947c0)
	/home/sparrowhawk/projects/soft/go/pkg/mod/maunium.net/go/mauview@v0.1.2/box.go:172 +0x17f
maunium.net/go/mauview.(*Centerer).Draw(0xc000518b00, 0x7ff44329d4c0, 0xc0001ee400)
	/home/sparrowhawk/projects/soft/go/pkg/mod/maunium.net/go/mauview@v0.1.2/center.go:103 +0xc4
maunium.net/go/gomuks/ui.(*MainView).Draw(0xc00013a4d0, 0x7ff44329d4c0, 0xc0001ee400)
	ui/view-main.go:113 +0x91
maunium.net/go/mauview.(*Application).redraw(0xc0003f94a0)
	/home/sparrowhawk/projects/soft/go/pkg/mod/maunium.net/go/mauview@v0.1.2/application.go:221 +0x99
maunium.net/go/mauview.(*Application).Start(0xc0003f94a0, 0x0, 0x0)
	/home/sparrowhawk/projects/soft/go/pkg/mod/maunium.net/go/mauview@v0.1.2/application.go:173 +0x43c
maunium.net/go/gomuks/ui.(*GomuksUI).Start(0xc0003f2d50, 0xd7fbe0, 0xc0003f2d20)
	ui/ui.go:73 +0x2f
main.(*Gomuks).Start(0xc0003f2d20)
	gomuks.go:115 +0x11d
main.main()
	main.go:83 +0x58
```

It doesn't dump core though, so I cannot give much more information. Terminal is urxvt. Please ask if I can provide any additional information.

**Comment by kotajacob** [comment]
This is happening with the latest tagged release for me too, but not with the latest git build. Using st on void.

**Comment by Mynacol** [comment]
Something similar happens to me on gomuks v0.2.1 (`gomuks` from AUR).
My terminal is Alacritty.
The debug.log says:
```
======================= Debug init @ 2020-12-07 15:29:52 =======================
[2020-12-07 15:29:52] Initializing syncer
[2020-12-07 15:29:52] Setting existing rooms
[2020-12-07 15:29:52] OnLogin() done.
[2020-12-07 15:29:52] Starting sync...
[2020-12-07 15:29:52] [Matrix] GET https://mynacol.xyz/_matrix/client/r0/sync?filter=2&since=s94962_8515015_133_125164_4965_28_1117_370153_123&timeout=30000
[2020-12-07 15:29:52] Received sync response
[2020-12-07 15:29:52] [Crypto/Trace] Device list changes in /sync: [@andreio:mozilla.org]
[2020-12-07 15:29:52] [Crypto/Debug] Sync response said we have 0 signed curve25519 keys left, sharing new ones...
[2020-12-07 15:29:52] [Crypto/Trace] Going to upload initial account keys
```

**Comment by alexmyczko** [comment]
Is this this? https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1053363
