### ISSUE TITLE
Crash on quit

### ISSUE THREAD

**Issue by georgkrause** [tulir/gomuks#252]
At first, thanks for providing the only matrix client with E2EE without wasting a huge amount of memory <3

Today I updated to the latest release. Since than I can't quit gomuks anymore. On running quit the first time, nothing happens. The second time, it crashes:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x847b65]

goroutine 38 [running]:
maunium.net/go/gomuks/debug.Recover()
	debug/debug.go:109 +0x98
panic(0xc15080, 0x1314060)
	/usr/lib/go/src/runtime/panic.go:969 +0x1b9
maunium.net/go/gomuks/matrix.(*HistoryManager).Close(...)
	matrix/history.go:85
maunium.net/go/gomuks/matrix.(*Container).Stop(0xc0000bc8c0)
	matrix/matrix.go:285 +0x105
main.(*Gomuks).Stop(0xc0002dbc20, 0xc0000ac701)
	gomuks.go:90 +0x77
maunium.net/go/gomuks/ui.cmdQuit(0xc0000740a0)
	ui/commands.go:444 +0x39
maunium.net/go/gomuks/ui.(*CommandProcessor).HandleCommand(0xc000346050, 0xc0000740a0)
	ui/command-processor.go:264 +0x107
created by maunium.net/go/gomuks/ui.(*RoomView).InputSubmit
	ui/room-view.go:685 +0x9c
```

If more information is needed, let me know.

**Comment by georgkrause** [comment]
This was probably caused by using old data, after deleting them and the cache, it does not occur anymore. I still have the data in the backups, so I might be able to test a fix.
