### ISSUE TITLE
unexpected end of JSON input

### ISSUE THREAD

**Issue by normen** [tulir/gomuks#255]
```
panic: unexpected end of JSON input [recovered]
        panic: unexpected end of JSON input

goroutine 1 [running]:
maunium.net/go/gomuks/debug.Recover()
        /Users/normenhansen/Dev/GoCode/gomuks/debug/debug.go:109 +0x98
panic(0x4820360, 0xc0001fa640)
        /usr/local/Cellar/go/1.15.6/libexec/src/runtime/panic.go:969 +0x1b9
maunium.net/go/gomuks/config.(*Config).load(0xc0004c1040, 0x48fb6d5, 0xa, 0xc0004f2210, 0x29, 0x49167a2, 0xe, 0x47e61e0, 0xc0004c1160)
        /Users/normenhansen/Dev/GoCode/gomuks/config/config.go:229 +0x56b
maunium.net/go/gomuks/config.(*Config).LoadPushRules(...)
        /Users/normenhansen/Dev/GoCode/gomuks/config/config.go:195
maunium.net/go/gomuks/config.(*Config).LoadAll(0xc0004c1040)
        /Users/normenhansen/Dev/GoCode/gomuks/config/config.go:147 +0x23c
main.NewGomuks(0x499f3d8, 0xc0004e64c0, 0x36, 0xc0004e6500, 0x36, 0xc0004f2210, 0x29, 0xc0004f0a40, 0x1d, 0xc00047bf18)
        /Users/normenhansen/Dev/GoCode/gomuks/gomuks.go:50 +0x17c
main.main()
        /Users/normenhansen/Dev/GoCode/gomuks/main.go:76 +0x48a
```

Just started doing this after a reboot. Tried deleting all settings from `~/Library/Application Support/gomuks` as well as `rm -rf ~/.config/gomuks ~/.cache/gomuks ~/.local/share/gomuks`

**Comment by normen** [comment]
So apparently on MacOS you have to delete `~/Library/Caches/gomuks` as well as `~/Library/Application Support/gomuks` to completely reset the application..

No idea what messed up the push rules file..
