### ISSUE TITLE
Fatal Error has occurred (stack dump)

### ISSUE THREAD

**Issue by Asara** [tulir/gomuks#296]
Running on a risc-v box so that might be part of the cause... but
```
runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack(0xe3e618, 0x3f98591b60, 0x3f600858f0)
        /usr/lib/go-1.16/src/runtime/debug/stack.go:24 +0xa4
maunium.net/go/gomuks/debug.PrettyPanic(0x8f1700, 0x12d93b0)
        /home/asara/.go/src/github.com/tulir/gomuks/debug/debug.go:133 +0x1d8
maunium.net/go/gomuks/debug.Recover()
        /home/asara/.go/src/github.com/tulir/gomuks/debug/debug.go:107 +0x6c
panic(0x8f1700, 0x12d93b0)
        /usr/lib/go-1.16/src/runtime/panic.go:965 +0x15c
maunium.net/go/mauview.(*Application).Start.func1(0x3f985192c0)
        /home/asara/.go/pkg/mod/maunium.net/go/mauview@v0.1.2/application.go:104 +0x8c
panic(0x8f1700, 0x12d93b0)
        /usr/lib/go-1.16/src/runtime/panic.go:965 +0x15c
maunium.net/go/mauview.(*Application).redraw(0x3f985192c0)
        /home/asara/.go/pkg/mod/maunium.net/go/mauview@v0.1.2/application.go:220 +0x28
maunium.net/go/mauview.(*Application).Start(0x3f985192c0, 0x0, 0x0)
        /home/asara/.go/pkg/mod/maunium.net/go/mauview@v0.1.2/application.go:156 +0x358
maunium.net/go/gomuks/ui.(*GomuksUI).Start(0x3f9843fb90, 0xa7c888, 0x3f9843fb60)
        /home/asara/.go/src/github.com/tulir/gomuks/ui/ui.go:75 +0x30
main.(*Gomuks).Start(0x3f9843fb60)
        /home/asara/.go/src/github.com/tulir/gomuks/gomuks.go:115 +0x11c
main.main()
        /home/asara/.go/src/github.com/tulir/gomuks/main.go:88 +0x624
```

**Comment by Asara** [comment]
First crash since that last one above. 

```
runtime error: invalid memory address or nil pointer dereference
goroutine 6126 [running]:
runtime/debug.Stack(0xe3e618, 0x3fb0814810, 0x3fb00e1a20)
        /usr/lib/go-1.16/src/runtime/debug/stack.go:24 +0xa4
maunium.net/go/gomuks/debug.PrettyPanic(0x8f1700, 0x12d93b0)
        /home/asara/.go/src/github.com/tulir/gomuks/debug/debug.go:133 +0x1d8
maunium.net/go/gomuks/debug.Recover()
        /home/asara/.go/src/github.com/tulir/gomuks/debug/debug.go:107 +0x6c
panic(0x8f1700, 0x12d93b0)
        /usr/lib/go-1.16/src/runtime/panic.go:965 +0x15c
maunium.net/go/gomuks/matrix.(*HistoryManager).Load(0x0, 0x3fb0158780, 0x32, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/asara/.go/src/github.com/tulir/gomuks/matrix/history.go:222 +0x44
maunium.net/go/gomuks/matrix.(*Container).GetHistory(0x3fb0566690, 0x3fb0158780, 0x32, 0x0, 0x3fb091da40, 0x1, 0x3fb403efb0, 0x1a0, 0x3f783489c0, 0x86290)
        /home/asara/.go/src/github.com/tulir/gomuks/matrix/matrix.go:1087 +0x4c
maunium.net/go/gomuks/ui.(*MainView).LoadHistory(0x3fb015a000, 0x3fb002aa20, 0x1e)
        /home/asara/.go/src/github.com/tulir/gomuks/ui/view-main.go:452 +0x174
created by maunium.net/go/gomuks/ui.(*MainView).switchRoom
        /home/asara/.go/src/github.com/tulir/gomuks/ui/view-main.go:268 +0x258
```
