### ISSUE TITLE
Fatal error log

### ISSUE THREAD

**Issue by donpdonp** [tulir/gomuks#413]
This is the first time ive seen gomuks crash. I dont remember exactly what was happening when it crashed.

```
runtime error: index out of range [17] with length 17
goroutine 1 [running]:
runtime/debug.Stack(0x13f0ce0, 0xc000d56810, 0xc000a93720)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
maunium.net/go/gomuks/debug.PrettyPanic(0xef7a40, 0xc0000de0f0)
	/builds/tulir/gomuks/debug/debug.go:133 +0x245
maunium.net/go/gomuks/debug.Recover()
	/builds/tulir/gomuks/debug/debug.go:107 +0x65
panic(0xef7a40, 0xc0000de0f0)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
maunium.net/go/mauview.(*Application).Start.func1(0xc00060c1e0)
	/builds/tulir/gomuks/.cache/pkg/mod/maunium.net/go/mauview@v0.1.2/application.go:104 +0x87
panic(0xef7a40, 0xc0000de0f0)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
maunium.net/go/mauview.(*InputArea).snapshot(0xc00036d2c0, 0x0)
	/builds/tulir/gomuks/.cache/pkg/mod/maunium.net/go/mauview@v0.1.2/inputarea.go:234 +0x331
maunium.net/go/mauview.(*InputArea).OnKeyEvent(0xc00036d2c0, 0x1400018, 0xc000948000, 0xc000d50cb8)
	/builds/tulir/gomuks/.cache/pkg/mod/maunium.net/go/mauview@v0.1.2/inputarea.go:1042 +0xea
maunium.net/go/gomuks/ui.(*RoomView).OnKeyEvent(0xc00036d400, 0x1400018, 0xc000948000, 0x19588e0)
	/builds/tulir/gomuks/ui/room-view.go:378 +0x172
maunium.net/go/mauview.(*Box).OnKeyEvent(0xc0001762a0, 0x1400018, 0xc000948000, 0xc7f398)
	/builds/tulir/gomuks/.cache/pkg/mod/maunium.net/go/mauview@v0.1.2/box.go:196 +0x5a
maunium.net/go/mauview.(*Flex).OnKeyEvent(...)
	/builds/tulir/gomuks/.cache/pkg/mod/maunium.net/go/mauview@v0.1.2/flex.go:116
maunium.net/go/gomuks/ui.(*MainView).OnKeyEvent(0xc0004ce630, 0x1400018, 0xc000948000, 0x0)
	/builds/tulir/gomuks/ui/view-main.go:204 +0x1e4
maunium.net/go/mauview.(*Application).Start(0xc00060c1e0, 0x0, 0x0)
	/builds/tulir/gomuks/.cache/pkg/mod/maunium.net/go/mauview@v0.1.2/application.go:155 +0x390
maunium.net/go/gomuks/ui.(*GomuksUI).Start(0xc000156420, 0x10266d8, 0xc0001563c0)
	/builds/tulir/gomuks/ui/ui.go:75 +0x2f
main.(*Gomuks).Start(0xc0001563c0)
	/builds/tulir/gomuks/gomuks.go:115 +0x11d
main.main()
	/builds/tulir/gomuks/main.go:89 +0x7c5
```

**Comment by donpdonp** [comment]
I want to add I love gomuks and use it every day. Thanks to everyone who works on gomuks.

**Comment by tulir** [comment]
That looks like an old version

**Comment by donpdonp** [comment]
okay i've updated my client. thx.
