### ISSUE TITLE
Panic at login

### ISSUE THREAD

**Issue by tulir** [tulir/gomuks#67]
```
runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack(0x8ffa40, 0xc4200b41c0, 0xc42005d9e0)
	runtime/debug/stack.go:24 +0xa7
maunium.net/go/gomuks/debug.PrettyPanic(0x825080, 0xb142b0)
	maunium.net/go/gomuks/debug/debug.go:97 +0x292
maunium.net/go/gomuks/debug.Recover()
	maunium.net/go/gomuks/debug/debug.go:72 +0x63
panic(0x825080, 0xb142b0)
	runtime/panic.go:502 +0x229
maunium.net/go/gomatrix.(*Client).SetCredentials(...)
	maunium.net/go/gomatrix/client.go:95
maunium.net/go/gomuks/matrix.(*Container).Login(0xc42009ee10, 0xc4200c5280, 0x12, 0xc420484246, 0x32, 0xc420000208, 0xc4200002b8)
	maunium.net/go/gomuks/matrix/matrix.go:131 +0x108
maunium.net/go/gomuks/ui.(*LoginView).Login(0xc42009ef00)
	maunium.net/go/gomuks/ui/view-login.go:90 +0x24a
maunium.net/go/gomuks/ui.(*LoginView).Login-fm()
	maunium.net/go/gomuks/ui/view-login.go:63 +0x2a
maunium.net/go/tview.(*Button).InputHandler.func1(0xc420475900, 0xc4203b6320)
	maunium.net/go/tview/button.go:129 +0x68
maunium.net/go/tview.(*Box).WrapInputHandler.func1(0xc420475900, 0xc4203b6320)
	maunium.net/go/tview/box.go:156 +0x5d
maunium.net/go/tview.(*Application).Run(0xc4200c6480, 0x8, 0x7bfbb6)
	maunium.net/go/tview/application.go:167 +0x4a4
maunium.net/go/gomuks/ui.(*GomuksUI).Start(0xc4201dcba0, 0x8cb1b0, 0xc4201dcb10)
	maunium.net/go/gomuks/ui/ui.go:68 +0x2f
main.(*Gomuks).Start(0xc4201dcb10)
	maunium.net/go/gomuks/gomuks.go:112 +0x11c
main.main()
	maunium.net/go/gomuks/main.go:38 +0x8a
```

**Comment by TobiasMie** [comment]
I had the same problem. As I understand the login procedure finishes successfully but it has no access to the server afterwards.
```
[2019-03-07 13:11:17] Initializing syncer
[2019-03-07 13:11:17] Setting existing rooms
[2019-03-07 13:11:17] OnLogin() done.
[2019-03-07 13:11:17] Starting sync...
[2019-03-07 13:11:17] [Matrix] POST /_matrix/client/r0/user/@user:server.org/filter {"account_data":{"types":["m.push_rules","m.direct","net.maunium.gomuks.preferences"]},"presence":{},"room":{"account_data":{"types":["m.tag"]},"ephemeral":{"types":["m.typing","m.receipt"]},"state":{"types":["m.room.member","m.room.name","m.room.topic","m.room.canonical_alias","m.room.aliases"]},"timeline":{"limit":50,"types":["m.room.message","m.room.member","m.room.name","m.room.topic","m.room.canonical_alias","m.room.aliases"]}}}
[2019-03-07 13:11:18] Sync() errored with  msg=Failed to POST JSON to /_matrix/client/r0/user/@user:server.org/filter code=401 wrapped=M_UNKNOWN_TOKEN: Unrecognised access token.  -> logging out
[2019-03-07 13:11:18] [Matrix] POST /_matrix/client/r0/logout {}
[2019-03-07 13:11:18] Stopping Matrix container...
[2019-03-07 13:11:18] Stopping sync...
[2019-03-07 13:11:26] Logging into https://server.org as @user:server.org...
[2019-03-07 13:11:26] Init error: <nil>
[2019-03-07 13:11:26] Initializing syncer
[2019-03-07 13:11:26] [Matrix] POST /_matrix/client/r0/login {"type":"m.login.password","password":"secret","user":"@user:server.org","initial_device_display_name":"gomuks"}
[2019-03-07 13:11:26] Setting existing rooms
[2019-03-07 13:11:26] OnLogin() done.
[2019-03-07 13:11:26] Starting sync...
[2019-03-07 13:11:26] [Matrix] POST /_matrix/client/r0/user/@user:server.org/filter {"account_data":{"types":["m.push_rules","m.direct","net.maunium.gomuks.preferences"]},"presence":{},"room":{"account_data":{"types":["m.tag"]},"ephemeral":{"types":["m.typing","m.receipt"]},"state":{"types":["m.room.member","m.room.name","m.room.topic","m.room.canonical_alias","m.room.aliases"]},"timeline":{"limit":50,"types":["m.room.message","m.room.member","m.room.name","m.room.topic","m.room.canonical_alias","m.room.aliases"]}}}
[2019-03-07 13:11:26] Sync() errored with  msg=Failed to POST JSON to /_matrix/client/r0/user/@user:server.org/filter code=401 wrapped=M_UNKNOWN_TOKEN: Unrecognised access token.  -> logging out
[2019-03-07 13:11:26] [Matrix] POST /_matrix/client/r0/logout {}
[2019-03-07 13:11:26] Stopping Matrix container...
[2019-03-07 13:11:26] Stopping sync...
```

**Comment by tulir** [comment]
This is probably fixed by now
