### ISSUE TITLE
Message parsing panics

### ISSUE THREAD

**Issue by tulir** [tulir/gomuks#81]
```
runtime error: invalid memory address or nil pointer dereference
goroutine 22 [running]:
runtime/debug.Stack(0x941be0, 0xc0000ae000, 0xc000659500)
	/runtime/debug/stack.go:24 +0xa7
maunium.net/go/gomuks/debug.PrettyPanic(0x848f80, 0xc37310)
	maunium.net/go/gomuks/debug/debug.go:97 +0x292
maunium.net/go/gomuks/debug.Recover()
	maunium.net/go/gomuks/debug/debug.go:72 +0x64
panic(0x848f80, 0xc37310)
	/runtime/panic.go:513 +0x1b9
maunium.net/go/gomuks/ui/messages/parser.ParseMessage(0x9492a0, 0xc0000b0d20, 0xc00014a600, 0xc0004c2480, 0xc000659800, 0xc000659940)
	maunium.net/go/gomuks/ui/messages/parser/parser.go:65 +0x821
maunium.net/go/gomuks/ui/messages/parser.ParseEvent(0x9492a0, 0xc0000b0d20, 0xc00014a600, 0xc0004c2480, 0xc000228708, 0xc00008ad01)
	maunium.net/go/gomuks/ui/messages/parser/parser.go:41 +0xb4
maunium.net/go/gomuks/ui.(*MainView).ParseEvent(0xc0001f4b60, 0x948320, 0xc0000f24d0, 0xc0004c2480, 0xc0000f24d0, 0x0)
	maunium.net/go/gomuks/ui/view-main.go:516 +0x64
maunium.net/go/gomuks/matrix.(*Container).HandleMessage(0xc0000b0d20, 0x22, 0xc0004c2480)
	maunium.net/go/gomuks/matrix/matrix.go:283 +0xdb
maunium.net/go/gomuks/matrix.(*Container).HandleMessage-fm(0x22, 0xc0004c2480)
	maunium.net/go/gomuks/matrix/matrix.go:196 +0x3e
maunium.net/go/gomuks/matrix.(*GomuksSyncer).notifyListeners(0xc000086210, 0x22, 0xc0004c2480)
	maunium.net/go/gomuks/matrix/sync.go:145 +0x97
maunium.net/go/gomuks/matrix.(*GomuksSyncer).processSyncEvent(0xc000086210, 0xc00014a600, 0xc0004c2480, 0x22)
	maunium.net/go/gomuks/matrix/sync.go:126 +0x6f
maunium.net/go/gomuks/matrix.(*GomuksSyncer).processSyncEvents(0xc000086210, 0xc00014a600, 0xc0000d8060, 0x1, 0x4, 0x22, 0xc000659b00)
	maunium.net/go/gomuks/matrix/sync.go:114 +0x76
maunium.net/go/gomuks/matrix.(*GomuksSyncer).ProcessResponse(0xc000086210, 0xc00066e000, 0xc000016200, 0x35, 0x35, 0x1)
	maunium.net/go/gomuks/matrix/sync.go:78 +0x2b6
maunium.net/go/gomuks/vendor/maunium.net/go/mautrix.(*Client).Sync(0xc000206240, 0xc0001562a0, 0x0)
	maunium.net/go/gomuks/vendor/maunium.net/go/mautrix/client.go:160 +0x270
maunium.net/go/gomuks/matrix.(*Container).Start(0xc0000b0d20)
	maunium.net/go/gomuks/matrix/matrix.go:238 +0x103
created by maunium.net/go/gomuks/matrix.(*Container).Login
	maunium.net/go/gomuks/matrix/matrix.go:144 +0x189
```
```
runtime error: invalid memory address or nil pointer dereference
goroutine 36 [running]:
runtime/debug.Stack(0x941be0, 0xc00036e1c0, 0xc000681500)
	/runtime/debug/stack.go:24 +0xa7
maunium.net/go/gomuks/debug.PrettyPanic(0x848f80, 0xc37310)
	maunium.net/go/gomuks/debug/debug.go:97 +0x292
maunium.net/go/gomuks/debug.Recover()
	maunium.net/go/gomuks/debug/debug.go:72 +0x64
panic(0x848f80, 0xc37310)
	/runtime/panic.go:513 +0x1b9
maunium.net/go/gomuks/ui/messages/parser.ParseMessage(0x9492a0, 0xc0000b0d20, 0xc000148600, 0xc000352000, 0xc000681800, 0xc000681940)
	maunium.net/go/gomuks/ui/messages/parser/parser.go:65 +0x821
maunium.net/go/gomuks/ui/messages/parser.ParseEvent(0x9492a0, 0xc0000b0d20, 0xc000148600, 0xc000352000, 0xc000324648, 0xc0002c0001)
	maunium.net/go/gomuks/ui/messages/parser/parser.go:41 +0xb4
maunium.net/go/gomuks/ui.(*MainView).ParseEvent(0xc00036e000, 0x948320, 0xc0000f24d0, 0xc000352000, 0xc0000f24d0, 0x1)
	maunium.net/go/gomuks/ui/view-main.go:516 +0x64
maunium.net/go/gomuks/matrix.(*Container).HandleMessage(0xc0000b0d20, 0x22, 0xc000352000)
	maunium.net/go/gomuks/matrix/matrix.go:283 +0xdb
maunium.net/go/gomuks/matrix.(*Container).HandleMessage-fm(0x22, 0xc000352000)
	maunium.net/go/gomuks/matrix/matrix.go:196 +0x3e
maunium.net/go/gomuks/matrix.(*GomuksSyncer).notifyListeners(0xc00052a090, 0x22, 0xc000352000)
	maunium.net/go/gomuks/matrix/sync.go:145 +0x97
maunium.net/go/gomuks/matrix.(*GomuksSyncer).processSyncEvent(0xc00052a090, 0xc000148600, 0xc000352000, 0x22)
	maunium.net/go/gomuks/matrix/sync.go:126 +0x6f
maunium.net/go/gomuks/matrix.(*GomuksSyncer).processSyncEvents(0xc00052a090, 0xc000148600, 0xc00057c120, 0x1, 0x4, 0x22, 0xc000681b00)
	maunium.net/go/gomuks/matrix/sync.go:114 +0x76
maunium.net/go/gomuks/matrix.(*GomuksSyncer).ProcessResponse(0xc00052a090, 0xc000092a80, 0xc0004663c0, 0x35, 0x35, 0x1)
	maunium.net/go/gomuks/matrix/sync.go:78 +0x2b6
maunium.net/go/gomuks/vendor/maunium.net/go/mautrix.(*Client).Sync(0xc0001cc480, 0xc0001550a0, 0x0)
	maunium.net/go/gomuks/vendor/maunium.net/go/mautrix/client.go:160 +0x270
maunium.net/go/gomuks/matrix.(*Container).Start(0xc0000b0d20)
	maunium.net/go/gomuks/matrix/matrix.go:238 +0x103
created by maunium.net/go/gomuks/matrix.(*Container).InitClient
	maunium.net/go/gomuks/matrix/matrix.go:118 +0x164
```

**Comment by tulir** [comment]
Was caused by outdated server, though not being able to find an event being replied to would probably cause the same panic.

**Comment by tulir** [comment]
I think this is fixed
