### ISSUE TITLE
crash when trying to start under byobu on arch

### ISSUE THREAD

**Issue by LaPingvino** [tulir/gomuks#86]
```
terminal entry not found
goroutine 1 [running]:
runtime/debug.Stack(0x94b840, 0xc00019a000, 0xc00023bd58)
        /usr/lib/go/src/runtime/debug/stack.go:24 +0xa7
maunium.net/go/gomuks/debug.PrettyPanic(0x8429e0, 0xc000077f20)
        /home/joop/gomuks/debug/debug.go:96 +0x292
maunium.net/go/gomuks/debug.Recover()
        /home/joop/gomuks/debug/debug.go:71 +0x64
panic(0x8429e0, 0xc000077f20)
        /usr/lib/go/src/runtime/panic.go:513 +0x1b9
main.(*Gomuks).Start(0xc000188f90)
        /home/joop/gomuks/gomuks.go:113 +0x149
main.main()
        /home/joop/gomuks/main.go:38 +0x85
```

**Comment by LaPingvino** [comment]
starting with TERM=screen gomuks seems to fix the issue
echo $TERM gives screen-256color-bce

**Comment by LaPingvino** [comment]
the -bce part seems not supported. I will file a Pull Request for https://github.com/tulir/tcell

**Comment by LaPingvino** [comment]
Pull request at https://github.com/tulir/tcell/pull/1

**Comment by tulir** [comment]
Should be fixed in the lates version of my tcell fork
