### ISSUE TITLE
Crash on start (with pantalaiom)

### ISSUE THREAD

**Issue by NotAFile** [tulir/gomuks#94]
When starting, I get a very weird behaviour. First it starts fine and starts syncing, but then after a few seconds a login is displayed. When I enter my credentials there, gomuks crashes after a few seconds:

```
runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack(0x941bc0, 0xc00008e850, 0xc0004f1868)
	/usr/lib/golang/src/runtime/debug/stack.go:24 +0xa7
maunium.net/go/gomuks/debug.PrettyPanic(0x848f80, 0xc38310)
	/home/nota/go/src/maunium.net/go/gomuks/debug/debug.go:97 +0x292
maunium.net/go/gomuks/debug.Recover()
	/home/nota/go/src/maunium.net/go/gomuks/debug/debug.go:72 +0x64
panic(0x848f80, 0xc38310)
	/usr/lib/golang/src/runtime/panic.go:513 +0x1b9
maunium.net/go/gomuks/vendor/maunium.net/go/tview.(*Application).Run.func1(0xc0001bad20)
	/home/nota/go/src/maunium.net/go/gomuks/vendor/maunium.net/go/tview/application.go:178 +0x8b
panic(0x848f80, 0xc38310)
	/usr/lib/golang/src/runtime/panic.go:513 +0x1b9
maunium.net/go/gomuks/vendor/maunium.net/go/mautrix.(*Client).SetCredentials(...)
	/home/nota/go/src/maunium.net/go/gomuks/vendor/maunium.net/go/mautrix/client.go:103
maunium.net/go/gomuks/matrix.(*Container).Login(0xc000090c80, 0xc000017620, 0x14, 0xc000271320, 0xe, 0x73d910, 0xc00016ea80)
	/home/nota/go/src/maunium.net/go/gomuks/matrix/matrix.go:139 +0xf8
maunium.net/go/gomuks/ui.(*LoginView).Login(0xc000090cd0)
	/home/nota/go/src/maunium.net/go/gomuks/ui/view-login.go:90 +0x245
maunium.net/go/gomuks/ui.(*LoginView).Login-fm()
	/home/nota/go/src/maunium.net/go/gomuks/ui/view-login.go:63 +0x2a
maunium.net/go/gomuks/vendor/maunium.net/go/tview.(*Button).InputHandler.func1(0xc00024e6c0, 0xc000011830)
	/home/nota/go/src/maunium.net/go/gomuks/vendor/maunium.net/go/tview/button.go:129 +0x68
maunium.net/go/gomuks/vendor/maunium.net/go/tview.(*Box).WrapInputHandler.func1(0xc00024e6c0, 0xc000011830)
	/home/nota/go/src/maunium.net/go/gomuks/vendor/maunium.net/go/tview/box.go:155 +0x5d
maunium.net/go/gomuks/vendor/maunium.net/go/tview.(*Application).Run(0xc0001bad20, 0x0, 0x0)
	/home/nota/go/src/maunium.net/go/gomuks/vendor/maunium.net/go/tview/application.go:259 +0x5b3
maunium.net/go/gomuks/ui.(*GomuksUI).Start(0xc000176d50, 0x8ecdb8, 0xc000176cc0)
	/home/nota/go/src/maunium.net/go/gomuks/ui/ui.go:68 +0x2f
main.(*Gomuks).Start(0xc000176cc0)
	/home/nota/go/src/maunium.net/go/gomuks/gomuks.go:112 +0x11c
main.main()
	/home/nota/go/src/maunium.net/go/gomuks/main.go:38 +0x85
```

This might very well be a pantalaiom bug, but gomuks crashing isn't a correct behaviour either way :P

**Comment by tulir** [comment]
hmm, just noticed

> tview

that's old (was old in May too I think)

Reopen if it happens on the latest version
